### ISSUE TITLE
Modifying data

### ISSUE THREAD

**Issue by tmeasday** [apollostack/client-docs#12]
Not sure if we want this bit to live here: http://docs.apollostack.com/apollo-client/mutations.html#mutation-results

**Comment by tmeasday** [comment]
Again, combined existing content from mutation and react sections, updated the examples to use githunt, and made sure it made sense.

@helfer / @Poincare -- review?

**Comment by helfer** [comment]
@tmeasday are you referring to a PR, or to the [link](http://docs.apollostack.com/apollo-client/mutations.html#mutation-results)?

**Comment by tmeasday** [comment]
Sorry @helfer : http://docs.apollostack.com/client/mutations.html

**Comment by helfer** [comment]
Ok! Here are some comments/questions:

- Do we really want to call them "query strings" and "mutation strings"? I would prefer just "query" and "mutation", unless it's a distinction we're making everywhere, in which case we should explain it (i.e. there's "query strings", "query documents" etc.)

> Basically, a query is the GraphQL equivalent of an HTTP GET and a mutation is the equivalent of an HTTP POST.
- I don't think we should include this sentence, because GraphQL by default sends everything via POST requests, and there's nothing that says you can't do a simple fetch with POST.

- For the code samples I thought we were going to use a simple Blog, Author, Post schema. Or do we want to use GitHunt now?

- In the second example it's a bit weird that created at is a number. Is that so people don't get confused about custom scalars if we include a date string there? If it's a number, then I think it should be a proper unix timestamp

> When we use mutations in Apollo typically result is integrated into the cache automatically based on the id of the result, which is reflected in your UI automatically, and we don’t explicitly handle the results ourselves. However, querying the fields that may have changed is important.
- This whole sentence is more confusing than clarifying. We should link to the section that explains how updates happen automatically in the store.

- In the basic mutation code sample, I wouldn't put ... anywhere. Just make the component really simple, but still make the code complete.

> The callback takes all the arguments
What does this refer to?

- What happens if you provide an optimisticResponse, but no updateQueries? In the case of new comments, would the UI even update without updateQueries when you insert a new comment? I thought that only works when you're modifying something that has an id.

**Comment by helfer** [comment]
I also made some minor modifications to fix a code sample and one sentence.

**Comment by tmeasday** [comment]
(by the way a lot of this content was just copied over from the existing client docs, so I didn't necessarily write)

1. fixed
2. fixed
3. I think we decided we wanted to use GitHunt. Am I making that up? @Poincare did it too ;)
4. This is just taken from GitHunt, but I agree its' weird. I'll pick a different feild.
5. I think you made it better? Do you still think we should fix it more?
6. Hmm, this is a good point. I want take the example from GitHunt but of course it makes no sense to include the full `render` function. Do you think we should just make up a render function to be clearer?
7. I think this was just a mistake
8. Yes, you are right. We don't have an example in GitHunt of modifying something... Do you think it make sense to do an `EditEntry` example here to follow on from the example above?

  Also should I say something about `updateQueries` yet? I think we should do another pass over this once we have all the other sections completed and we know what makes sense.

**Comment by tmeasday** [comment]
OK, this isn't as good as a PR. I'll make a PR for the queries chapter.

**Comment by tmeasday** [comment]
@helfer thoughts on my questions above?

**Comment by helfer** [comment]
Yeah, I'm a bit torn, because on the one hand I think it would be great to use actual code, but on the other hand I don't think we want to write a new and simpler example app from scratch... So I'd say 6) yeah, just make up a short example, and 8) I think we should actually add that functionality in GitHunt, just so we can demo it.

For 5), I think the sentence "However, querying the fields that may have changed is important." is still a bit confusing. What exactly do you mean with that? That developers should know which fields might have changed and include them in the query? Then it's not just important, they **must** do it.

We can cover updateQueries in the other parts, so maybe just mention it briefly.

**Comment by tmeasday** [comment]
Ok, next pass done. Close this issue if you are happy for now.
